  import type { Metadata } from "next";
  import localFont from "next/font/local";
  import "./globals.css";

  import { classNames } from "@/utils";
  import Footer from "@/components/Footer";

  export const everett = localFont({
    src: [
      {
        path: "../public/fonts/Everett-Regular.otf",
        style: "normal",
      },
    ],
    variable: "--font-everett",
  });

  export const lausanne = localFont({
    src: [
      {
        path: "../public/fonts/Lausanne-Regular.otf",
        style: "normal",
      },
    ],
    variable: "--font-lausanne",
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <body className={classNames(lausanne.className, everett.className,)}>
          {children}
          <Footer />
        </body>
      </html>
    );
  }
